GET http://localhost/tweets


###

GET http://localhost/tweets/1256385672174276600


###

GET http://localhost/indizes


###

GET http://localhost/indizes/^GDAXI


###

GET http://localhost/indizes/^GDAXI/2020-05-12 08:00:00